### ISSUE TITLE
NPE when modifying users entry via scim

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxCore#128]
By Apr 15th most SCIM cases were running successfully:
https://ox.gluu.org/jenkins/job/oxScimClient_4.0.0/47/console

In the latest CE package, I'm having the following for all operations involving user updates:

```
2019-04-25 14:09:35,341 ERROR [qtp804611486-129] [gluu.oxtrust.ws.rs.scim2.UserWebService] (UserWebService.java:179) - Failure at updateUser method
java.lang.NullPointerException: null
	at org.gluu.util.ArrayHelper.arrayClone(ArrayHelper.java:65) ~[oxcore-util-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.util.ArrayHelper.sortAndClone(ArrayHelper.java:76) ~[oxcore-util-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.util.ArrayHelper.equalsIgnoreOrder(ArrayHelper.java:84) ~[oxcore-util-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.persist.model.AttributeData.equals(AttributeData.java:82) ~[oxcore-persistence-core-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.persist.impl.BaseEntryManager.collectAttributeModifications(BaseEntryManager.java:376) ~[oxcore-persistence-core-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.persist.impl.BaseEntryManager.merge(BaseEntryManager.java:225) ~[oxcore-persistence-core-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.persist.ldap.impl.LdapEntryManager.merge(LdapEntryManager.java:115) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor484.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.gluu.persist.EntityManager$PersistenceEntryManager$479440844$Proxy$_$$_WeldClientProxy.merge(Unknown Source) ~[weld-core-impl-3.0.5.Final.jar:?]
	at org.gluu.oxtrust.ldap.service.PersonService.updatePerson(PersonService.java:135) ~[classes/:?]
	at org.gluu.oxtrust.service.scim2.Scim2UserService.replacePersonInfo(Scim2UserService.java:538) ~[classes/:?]
	at org.gluu.oxtrust.service.scim2.Scim2UserService.updateUser(Scim2UserService.java:513) ~[classes/:?]
	at org.gluu.oxtrust.ws.rs.scim2.UserWebService.updateUser(UserWebService.java:170) [classes/:?]
	at org.gluu.oxtrust.ws.rs.scim2.UserWebService$Proxy$_$$_WeldSubclass.updateUser(Unknown Source) [classes/:?]
	at org.gluu.oxtrust.service.scim2.interceptor.UserWebServiceDecorator.updateUser(UserWebServiceDecorator.java:140) [classes/:?]
```

SCIM code (server and client) haven't changed recently. The following are examples of test cases that lead to the error below:
https://github.com/GluuFederation/SCIM-Client/blob/master/src/test/java/gluu/scim2/client/singleresource/AverageUserTest.java#L75
https://github.com/GluuFederation/SCIM-Client/blob/master/src/test/java/gluu/scim2/client/singleresource/MinimalUserTest.java#L39

**Comment by yurem** [comment]
There is no this exception in recent build. I fixed this in another issue already.
