### ISSUE TITLE
Unable to add Trust Relationship

### ISSUE THREAD

**Issue by dhafley** [GluuFederation/oxCore#13]
I'm attempting to setup my first Trust Relationship with Gluu, so this could be my own issue and not an issue with the actual software.  But logging it here just in case others are experiencing.  

I've attempted to add a few different Service Providers to my Gluu server, both through File and URL metadata types.  

I'm unable to add TestShip Trust Relationship when following these docs: https://www.gluu.org/docs/integrate/test-shib2/#testshib2-testing-for-gluu-server

Here is the exception I see in wrapper.log:

```
INFO   | jvm 1    | 2016/11/22 17:33:26 | 2016-11-22 17:33:26,581 ERROR [org.xdi.util.io.HTTPFileDownloader] Failed to get resource http://www.testshib.org/metadata/testshib-providers.xml
INFO   | jvm 1    | 2016/11/22 17:33:26 | java.net.UnknownHostException: www.testshib.org
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at java.net.Socket.connect(Socket.java:579)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at java.net.Socket.connect(Socket.java:528)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at java.net.Socket.<init>(Socket.java:425)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at java.net.Socket.<init>(Socket.java:280)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(Unknown Source)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(Unknown Source)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.commons.httpclient.HttpConnection.open(Unknown Source)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.commons.httpclient.HttpClient.executeMethod(Unknown Source)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.commons.httpclient.HttpClient.executeMethod(Unknown Source)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.xdi.util.io.HTTPFileDownloader.getResource(HTTPFileDownloader.java:53)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.gluu.oxtrust.ldap.service.Shibboleth2ConfService.saveSpMetadataFile(Shibboleth2ConfService.java:614)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.gluu.oxtrust.ldap.service.Shibboleth2ConfService_$$_javassist_seam_4.saveSpMetadataFile(Shibboleth2ConfService_$$_javassist_seam_4.java)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.saveSpMetaDataFileSourceTypeURI(UpdateTrustRelationshipAction.java:776)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.save(UpdateTrustRelationshipAction.java:269)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.security.SecurityInterceptor.aroundInvoke(SecurityInterceptor.java:163)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.gluu.oxtrust.action.UpdateTrustRelationshipAction_$$_javassist_seam_57.save(UpdateTrustRelationshipAction_$$_javassist_seam_57.java)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:335)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:348)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.el.parser.AstPropertySuffix.invoke(AstPropertySuffix.java:58)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.el.parser.AstValue.invoke(AstValue.java:96)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:276)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:101)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at javax.faces.component.UICommand.broadcast(UICommand.java:315)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:786)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1251)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.web.MultipartFilter.doFilter(MultipartFilter.java:86)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
INFO   | jvm 1    | 2016/11/22 17:33:26 | 	at java.lang.Thread.run(Thread.java:745)
```

I've confirmed that I can wget the contents at the end of that url.
```
$ wget http://www.testshib.org/metadata/testshib-providers.xml
--2016-11-22 12:34:14--  http://www.testshib.org/metadata/testshib-providers.xml
Resolving www.testshib.org (www.testshib.org)... 128.118.137.147, 2610:8:0:81:b943:6d1:3851:49bf
Connecting to www.testshib.org (www.testshib.org)|128.118.137.147|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19630 (19K) [text/xml]
Saving to: ‘testshib-providers.xml’

100%[===================================================================================================================================================================================================================================>] 19,630      --.-K/s   in 0.03s

2016-11-22 12:34:15 (578 KB/s) - ‘testshib-providers.xml’ saved [19630/19630]
```

**Comment by willow9886** [comment]
See support ticket here: https://support.gluu.org/single-sign-on/3497/unable-to-add-trust-relationship/ 

Easiest for us to resolve issues on Gluu support. If it's in fact a bug, we will open a new issue.

Thank you.

**Comment by dhafley** [comment]
Yep, sorry about that.  I was in the process of trying to delete this issue but doesn't look possible.

**Comment by willow9886** [comment]
No problem, David. Thanks for the note.
