### ISSUE TITLE
N1QL filters not escaping quotes?

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxCore#145]
``` 
2019-09-11 21:02:03,522 INFO  [qtp105704967-12] [gluu.oxtrust.service.antlr.scimFilter.FilterListener]
(FilterListener.java:159) - LDAP filter expression computed was 

(|
	(oxTrustAddresses=*"type":null*)
	(!(oxTrustAddresses=*"postalCode":null*))
)

...

2019-09-11 21:02:03,536 ERROR [qtp105704967-12] [gluu.oxtrust.ws.rs.scim2.UserWebService] (UserWebService.java:235) - Failure at searchUsers method
org.gluu.persist.exception.EntryPersistenceException: Failed to find entries with key: people, expression: org.gluu.persist.couchbase.model.ConvertedExpression@201b5c7f
	at org.gluu.persist.couchbase.impl.CouchbaseEntryManager.findEntriesImpl(CouchbaseEntryManager.java:459) ~[oxcore-persistence-couchbase-4.0.0-SNAPSHOT.jar:?]

...

Caused by: org.gluu.persist.exception.operation.SearchException: Failed to search entries. Query: '

SELECT gluu_doc.*, dn 
FROM `gluu_user` AS gluu_doc 
WHERE 
( objectClass = "gluuPerson" ) AND 
( ( oxTrustAddresses LIKE "%"type":null%" OR ( NOT oxTrustAddresses LIKE "%"postalCode":null%" ) ) )
ORDER BY displayName LIMIT 200 OFFSET 0

. Error: '[{"msg":"syntax error - at type","code":3000}]', Error count: '1'
	at org.gluu.persist.couchbase.operation.impl.CouchbaseOperationsServiceImpl.searchImpl(CouchbaseOperationsServiceImpl.java:548) ~[oxcore-persistence-couchbase-4.0.0-SNAPSHOT.jar:?]
...
```

**Comment by jgomer2001** [comment]
I added line breaks for readability

The first filter expression (that looks like LDAP) is the output of a call to org.gluu.search.filter.Filter.toString() on the filter built

**Comment by yurem** [comment]
It calls JSON escpe in eq filter already. I added the same to like statement as well
