### ISSUE TITLE
ORM : date attributes are double converted which leads to exception

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxCore#150]
ORM : date attributes are double converted which leads to exception
```
17:51:20.896 [main] ERROR org.gluu.persist.couchbase.operation.impl.CouchbaseConnectionProvider - Failed to decode generalized time 'Thu Sep 19 17:51:20 EEST 2019'
java.text.ParseException: Unparseable date: "Thu Sep 19 17:51:20 EEST 2019"
    at java.text.DateFormat.parse(DateFormat.java:366) ~[?:1.8.0_77]
    at org.gluu.persist.couchbase.impl.CouchbaseEntryManager.decodeTime(CouchbaseEntryManager.java:866) [classes/:?]
    at org.gluu.persist.couchbase.impl.CouchbaseEntryManager.decodeTime(CouchbaseEntryManager.java:878) [classes/:?]
    at org.gluu.persist.impl.BaseEntryManager.setPropertyValue(BaseEntryManager.java:1485) [classes/:?]
    at org.gluu.persist.impl.BaseEntryManager.createEntities(BaseEntryManager.java:821) [classes/:?]
    at org.gluu.persist.impl.BaseEntryManager.createEntities(BaseEntryManager.java:752) [classes/:?]
    at org.gluu.persist.impl.BaseEntryManager.find(BaseEntryManager.java:602) [classes/:?]
    at org.gluu.persist.impl.BaseEntryManager.find(BaseEntryManager.java:486) [classes/:?]
    at org.gluu.persist.impl.BaseEntryManager.find(BaseEntryManager.java:474) [classes/:?]
    at org.gluu.service.cache.NativePersistenceCacheProvider.get(NativePersistenceCacheProvider.java:77) [classes/:?]
    at org.gluu.service.cache.CouchbaseNativeCacheTest.couchbaseCacheProvider(CouchbaseNativeCacheTest.java:47) [test-classes/:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85) [testng-6.9.4.jar:?]
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:659) [testng-6.9.4.jar:?]
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845) [testng-6.9.4.jar:?]
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153) [testng-6.9.4.jar:?]
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) [testng-6.9.4.jar:?]
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108) [testng-6.9.4.jar:?]
    at org.testng.TestRunner.privateRun(TestRunner.java:771) [testng-6.9.4.jar:?]
    at org.testng.TestRunner.run(TestRunner.java:621) [testng-6.9.4.jar:?]
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:357) [testng-6.9.4.jar:?]
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352) [testng-6.9.4.jar:?]
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310) [testng-6.9.4.jar:?]
    at org.testng.SuiteRunner.run(SuiteRunner.java:259) [testng-6.9.4.jar:?]
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.9.4.jar:?]
```

**Comment by yuriyz** [comment]
Fixed in 4.0
