### ISSUE TITLE
Fix LDAP removal with filter when entry not extends DeletableEntity

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxCore#167]
```
2019-11-28 14:40:22,268 INFO  [ForkJoinPool.commonPool-worker-0] [org.gluu.service.cache.NativePersistenceCacheProvider] (NativePersistenceCacheProvid
er.java:59) - Created NATIVE_PERSISTENCE cache provider. `baseDn`: ou=cache,o=gluu
2019-11-28 14:40:22,273 ERROR [ForkJoinPool.commonPool-worker-0] [org.gluu.service.cache.NativePersistenceCacheProvider] (NativePersistenceCacheProvid
er.java:210) - Failed to perform clean up.
org.gluu.persist.exception.EntryDeleteException: Failed to delete entries with baseDN: ou=cache,o=gluu, filter: (&(&(objectClass=cache))(&(del=true)(e
xp<=20191128144022.186Z)))
        at org.gluu.persist.ldap.impl.LdapEntryManager.remove(LdapEntryManager.java:339) ~[oxcore-persistence-ldap-4.0.1.Final.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.gluu.persist.EntityManager$PersistenceEntryManager$1948486608$Proxy$_$$_WeldClientProxy.remove(Unknown Source) ~[weld-core-impl-3.1.1.F
inal.jar:?]
        at org.gluu.service.cache.NativePersistenceCacheProvider.cleanup(NativePersistenceCacheProvider.java:206) [oxcore-service-4.0.1.Final.jar:?]
        at org.gluu.service.cache.NativePersistenceCacheProvider.cleanup(NativePersistenceCacheProvider.java:197) [oxcore-service-4.0.1.Final.jar:?]
        at org.gluu.service.cache.NativePersistenceCacheProvider$Proxy$_$$_WeldClientProxy.cleanup(Unknown Source) [oxcore-service-4.0.1.Final.jar:?]
        at org.gluu.service.cache.CacheProvider$Proxy$_$$_WeldClientProxy.cleanup(Unknown Source) [oxcore-service-4.0.1.Final.jar:?]
        at org.gluu.oxauth.service.CleanerTimer.processCache(CleanerTimer.java:214) [classes/:?]
        at org.gluu.oxauth.service.CleanerTimer.processImpl(CleanerTimer.java:162) [classes/:?]
        at org.gluu.oxauth.service.CleanerTimer$Proxy$_$$_WeldSubclass.processImpl(Unknown Source) [classes/:?]
        at org.gluu.oxauth.service.CleanerTimer.process(CleanerTimer.java:115) [classes/:?]
        at org.gluu.oxauth.service.CleanerTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
        at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld
-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.1.1.Final.j
ar:3.1.1.Final]
        at org.gluu.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-4.0.1.Final.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
Caused by: java.lang.ClassCastException: org.gluu.service.cache.NativePersistenceCacheEntity cannot be cast to org.gluu.persist.model.base.DeletableEn
tity
        at org.gluu.persist.ldap.impl.LdapEntryManager$DeleteBatchOperation.performAction(LdapEntryManager.java:959) ~[oxcore-persistence-ldap-4.0.1.F
inal.jar:?]
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.searchImpl(LdapOperationsServiceImpl.java:386) ~[oxcore-persistence-ldap-4.0
.1.Final.jar:?]
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.search(LdapOperationsServiceImpl.java:305) ~[oxcore-persistence-ldap-4.0.1.F
inal.jar:?]
        at org.gluu.persist.ldap.impl.LdapEntryManager.remove(LdapEntryManager.java:335) ~[oxcore-persistence-ldap-4.0.1.Final.jar:?]
        ... 28 more
```

**Comment by yurem** [comment]
Fixed
