### ISSUE TITLE
Load scripts during startup instead of send async even to load them after startup

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxCore#202]
This async load can led to issue when RP send request earlier than server load scripts first time:

```
020-03-19 11:14:30,320 ERROR [qtp1818402158-12] [org.gluu.oxauth.servlet.OpenIdConfiguration] (OpenIdConfiguration.java:301) - null
java.lang.NullPointerException: null
        at org.gluu.oxauth.service.external.ExternalAuthenticationService.getAcrValuesList(ExternalAuthenticationService.java:446) ~[classes/:?]
        at org.gluu.oxauth.service.external.ExternalAuthenticationService$Proxy$_$$_WeldClientProxy.getAcrValuesList(Unknown Source) ~[classes/:?]
        at org.gluu.oxauth.servlet.OpenIdConfiguration.processRequest(OpenIdConfiguration.java:130) ~[classes/:?]
```

**Comment by yurem** [comment]
Implemented
